name: Jest Tests

on: 
  push:
    branches:
      - jest-tests # Run on pushes to this branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Or your desired Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test 
